/*
 * SearchDialogImpl.java
 *
 * Created on 02.07.2011, 19:25:40
 */
package ru.yandex.test.impl;

import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.SwingWorker;
import javax.swing.UIManager;
import ru.yandex.test.SearchDialog;
import ru.yandex.test.SearchDoubles.Duplicate;
import ru.yandex.test.VacancySource;
import ru.yandex.test.VacancySet;

/**
 *
 * @author OneHalf
 */
public class SearchDialogImpl extends javax.swing.JFrame implements SearchDialog {

    /** Creates new form SearchDialogImpl */
    public SearchDialogImpl() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            Logger.getLogger(SearchDialogImpl.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        pnlSites = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel1.setText("Что ищем?");
        jPanel1.add(jLabel1);

        jTextField1.setPreferredSize(new java.awt.Dimension(120, 20));
        jPanel1.add(jTextField1);

        btnSearch.setText("Найти");
        jPanel1.add(btnSearch);

        btnReport.setText("Отчет");
        jPanel1.add(btnReport);

        jPanel2.add(jPanel1);

        jLabel2.setText("Где ищем?");
        pnlSites.add(jLabel2);

        jPanel2.add(pnlSites);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pnlSites;
    // End of variables declaration//GEN-END:variables

    private Map<JCheckBox, VacancySource> checkBoxes = new HashMap<JCheckBox, VacancySource>();
    
    @Override
    public String getSearchString() {
        return jTextField1.getText();
    }

    @Override
    public void addSearchListener(ActionListener listener) {
        btnSearch.addActionListener(listener);
    }

    @Override
    public void addReportListener(ActionListener listener) {
        btnReport.addActionListener(listener);
    }

    @Override
    public void setDuplicateVacancy(Set<Duplicate> duplicates) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void setSiteParsers(Set<VacancySource> siteParsers) {
        for (JCheckBox checkBox : checkBoxes.keySet()) {
            pnlSites.remove(checkBox);
        }
        checkBoxes.clear();
        
        for (VacancySource siteParser : siteParsers) {
            final JCheckBox jCheckBox = new JCheckBox(siteParser.getSourceName(), true);
            pnlSites.add(jCheckBox);
            checkBoxes.put(jCheckBox, siteParser);
        }
    }

    @Override
    public Set<VacancySource> getVacancySources() {
        HashSet<VacancySource> result = new HashSet<VacancySource>();
        
        for (JCheckBox checkbox : checkBoxes.keySet()) {
            if (checkbox.isSelected()) {
                result.add(checkBoxes.get(checkbox));
            }
        }
        return result;
    }
    
    private class ParserProcess extends SwingWorker<Set<Duplicate>, VacancySet> {

        @Override
        protected Set<Duplicate> doInBackground() throws Exception {
            throw new UnsupportedOperationException("Not supported yet.");
        }

        @Override
        protected void done() {
            super.done();
        }

        @Override
        protected void process(List<VacancySet> chunks) {
            super.process(chunks);
        }
        
    }
}
