/*
 * SearchDialog.java
 *
 * Created on 02.07.2011, 19:25:40
 */
package ru.yandex.test.impl;

import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.io.File;
import java.io.IOException;
import ru.yandex.test.Vacancy;
import ru.yandex.test.VacancySource;

import java.awt.event.ActionListener;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import java.util.logging.Handler;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.UIManager;

import org.springframework.beans.factory.BeanFactory;
import org.springframework.beans.factory.xml.XmlBeanFactory;
import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;

import ru.yandex.test.Duplicate;
import ru.yandex.test.ReportCreator;

/**
 *
 * @author OneHalf
 */
public class SearchDialog extends javax.swing.JFrame {

        private static BeanFactory beanFactory;
    private static final Double THRESHOLD_OF_EQUIVALENCE = 0.55;

    static {
        Resource resource = new FileSystemResource("src/ru/yandex/test/config.xml");
        beanFactory = new XmlBeanFactory(resource);
    }
    
    private ReportCreator reportCreator;
    private Set<Duplicate> lastResult;
    private VacancySource[] vacancySources;
    private static final Logger LOGGER = Logger.getLogger(SearchDialog.class.getName());
    
    private Map<JCheckBox, VacancyXmlFileParser> preparsedCheckBoxes = new HashMap<JCheckBox, VacancyXmlFileParser>();
    private Map<JCheckBox, SiteParser> siteCheckBoxes = new HashMap<JCheckBox, SiteParser>();

    /** Creates new form SearchDialog */
    public SearchDialog() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            Logger.getLogger(SearchDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taResult = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfSearchQuery = new javax.swing.JTextField();
        cbSearchInSelf = new javax.swing.JCheckBox();
        pnlSites = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tfItemCount = new javax.swing.JTextField();
        pnlFiles = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Сравнение вакансий");

        taResult.setColumns(20);
        taResult.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        taResult.setRows(5);
        jScrollPane1.setViewportView(taResult);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Что ищем?");
        jPanel1.add(jLabel1);

        tfSearchQuery.setPreferredSize(new java.awt.Dimension(120, 20));
        jPanel1.add(tfSearchQuery);

        cbSearchInSelf.setText("Искать дубли в пределах одного сайта");
        jPanel1.add(cbSearchInSelf);

        jPanel2.add(jPanel1);

        pnlSites.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("Где ищем?");
        pnlSites.add(jLabel2);

        jPanel2.add(pnlSites);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setText("Сколько ищем? (на каждый источник)");
        jPanel3.add(jLabel3);

        tfItemCount.setText("25");
        tfItemCount.setMinimumSize(new java.awt.Dimension(60, 20));
        tfItemCount.setPreferredSize(new java.awt.Dimension(60, 20));
        jPanel3.add(tfItemCount);

        jPanel2.add(jPanel3);

        pnlFiles.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setText("Уже собранная информация:");
        pnlFiles.add(jLabel4);

        jPanel2.add(pnlFiles);

        pnlButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btnSearch.setText("Найти");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        pnlButtons.add(btnSearch);

        btnReport.setText("Отчет");
        pnlButtons.add(btnReport);

        jPanel2.add(pnlButtons);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        loadVacancySet();
        Set<Duplicate> searchDuplicateVacancy = searchDuplicateVacancy();
        setDuplicateVacancy(searchDuplicateVacancy);
    }//GEN-LAST:event_btnSearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSearch;
    private javax.swing.JCheckBox cbSearchInSelf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlFiles;
    private javax.swing.JPanel pnlSites;
    private javax.swing.JTextArea taResult;
    private javax.swing.JTextField tfItemCount;
    private javax.swing.JTextField tfSearchQuery;
    // End of variables declaration//GEN-END:variables
    
    private String getSearchString() {
        return tfSearchQuery.getText();
    }

    private Set<Duplicate> seachDuplicatesInVacancySource(VacancySource vacancySource) {
        Set<Duplicate> result = new HashSet<Duplicate>();
        Vacancy[] vacancies = vacancySource.getVacancies().toArray(new Vacancy[]{});
        
        for (int i = 0; i < vacancies.length; i++) {
            for (int j = i+1; j < vacancies.length; j++) {
                 if (vacancies[i].getLevelOfSimilarity(vacancies[j]) > THRESHOLD_OF_EQUIVALENCE) {
                    result.add(new Duplicate(vacancies[i], vacancies[j]));
                    LOGGER.log(Level.FINE, "Найдены дубликаты: \n{0}, \n{1}",
                            new Object[]{vacancies[i], vacancies[j]});
                }
            }
        }
        return result;
    }

    private void setDuplicateVacancy(Set<Duplicate> duplicates) {
        lastResult = duplicates;
        StringBuilder sb = new StringBuilder();
        for (Duplicate duplicate : duplicates) {
            Vacancy firstVacancy = duplicate.getDuplicates().iterator().next();
            for (Vacancy vacancy : duplicate.getDuplicates()) {
                sb.append(vacancy.getVacancyName()).append(" ")
                        .append(vacancy.getVacancyUrl()).append("\n");
                if (vacancy != firstVacancy) {
                    sb.append("Похожесть: ")
                            .append((int)(100*firstVacancy.getLevelOfSimilarity(vacancy)))
                            .append("% \n");
                }
            }
            sb.append("\n");
        }
        
        taResult.setText(sb.toString());
    }

    public void setSiteParsers(Set<SiteParser> siteParsers) {
        for (JCheckBox checkBox : siteCheckBoxes.keySet()) {
            pnlSites.remove(checkBox);
        }
        siteCheckBoxes.clear();
        
        for (SiteParser siteParser : siteParsers) {
            final JCheckBox jCheckBox = new JCheckBox(siteParser.getSourceName(), true);
            pnlSites.add(jCheckBox);
            siteCheckBoxes.put(jCheckBox, siteParser);
        }
    }

    public void setPreparsedXmlFiles(Set<VacancyXmlFileParser> files) {
        for (JCheckBox checkBox : preparsedCheckBoxes.keySet()) {
            pnlFiles.remove(checkBox);
        }
        preparsedCheckBoxes.clear();
        
        for (VacancyXmlFileParser xmlFile : files) {
            final JCheckBox jCheckBox = new JCheckBox(xmlFile.getSourceName(), true);
            pnlFiles.add(jCheckBox);
            preparsedCheckBoxes.put(jCheckBox, xmlFile);
        }
    }

    private Set<VacancySource> getVacancySources() {
        Set<VacancySource> result = new HashSet<VacancySource>();
        
        for (JCheckBox checkbox : siteCheckBoxes.keySet()) {
            if (checkbox.isSelected()) {
                result.add(siteCheckBoxes.get(checkbox));
            }
        }
        for (JCheckBox checkbox : preparsedCheckBoxes.keySet()) {
            if (checkbox.isSelected()) {
                result.add(preparsedCheckBoxes.get(checkbox));
            }
        }
        return result;
    }

    private int getItemsCount() {
        return Integer.parseInt(tfItemCount.getText());
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        final Logger ROOT_LOGGER = Logger.getLogger("ru.yandex.test");
        ROOT_LOGGER.setLevel(Level.INFO);
        final LogFormatter logFormatter = new LogFormatter();
        for (Handler handler : ROOT_LOGGER.getHandlers()) {
            handler.setFormatter(logFormatter);
        }
        beanFactory.getBean("dialog");
    }
            
    public void setReportCreator(ReportCreator reportCreator) {
        this.reportCreator = reportCreator;
        this.btnReport.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    File fileResult = SearchDialog.this.reportCreator.getReport(lastResult);
                    Desktop.getDesktop().open(fileResult);
                } catch (IOException ex) {
                    Logger.getLogger(SearchDialog.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public void loadVacancySet() {
        vacancySources = this.getVacancySources().toArray(new VacancySource[]{});
        for (SiteParser siteParser : siteCheckBoxes.values()) {
            siteParser.setSearchText(this.getSearchString());
            siteParser.setItemsCount(this.getItemsCount());
        }
    }
    
    private Set<Duplicate> searchDuplicateVacancy() {
        LOGGER.log(Level.FINE, "Поиск дубликатов");
        
        Set<Duplicate> result = new HashSet<Duplicate>();
        
        for (int i = 0; i < vacancySources.length; i++) {
            for (int j = i+1; j < vacancySources.length; j++) {
                for (Vacancy k : vacancySources[i].getVacancies()) {
                    for (Vacancy l : vacancySources[j].getVacancies()) {
                        if (k.getLevelOfSimilarity(l) > THRESHOLD_OF_EQUIVALENCE) {
                            result.add(new Duplicate(k, l));
                            LOGGER.log(Level.FINE, "Найдены дубликаты: \n{0}, \n{1}",
                                    new Object[]{k, l});
                        }
                    }                    
                }
            }
        }
        LOGGER.log(Level.FINER, "Окончание поиска дубликатов");
        
        if (cbSearchInSelf.isSelected()) {
            for (VacancySource vacancySource : vacancySources) {
                result.addAll(seachDuplicatesInVacancySource(vacancySource));
            }
        }
        return result;
    }
}
